name: First Job
on: [push]
jobs:
    build-app: 
        runs-on: ubuntu-latest
        steps: 
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with: 
            node-version: "16.13.1"
        - name: "Install node modules"
          run: yarn
        - name: "Building the project"
          run: yarn build
        - name: "Finished"
          run: echo "Done..."
    dependent:
        needs: build-app
        runs-on: ubuntu-latest
        steps:
            - run: echo "Dependent on build-app"
