name: First Job
on: [push]
jobs:
    build-app: 
        runs-on: ubuntu-latest
        outputs:
            text: ${{ steps.finished.outputs.text }}
        steps: 
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with: 
            node-version: "16.13.1"
        - name: "Install node modules"
          run: yarn
        - name: "Building the project"
          run: yarn build
        - name: "Finished"
          id: finished
          run: echo "::set-output name=text::hello-from-build"
    dependent:
        needs: build-app
        runs-on: ubuntu-latest
        env: 
            Build_Output: ${{ needs.build-app.outputs.text }}
        steps:
            - name: Echo Dependent
              run: echo "Dependent on build-app"
            - name: Build Variable
              run: echo $Build_Output
