name: First Job
on: [push]
jobs:
    build-app: 
        runs-on: ubuntu-latest
        steps: 
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with: 
            node-version: "16.13.1"
<<<<<<< HEAD
        - name: "Building the project"
          run: yarn build
        - name: "Finished"
          run: echo "Done..."
=======
        - run: "node -v"
>>>>>>> 3e6078d9bdd2c811c253d3409acd1c7287a9198d
